// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2TPQhLV1kUZRgLxrsy4emLwxzYe0kW_s',
    appId: '1:729784385247:android:bd05622bfde62ea718b36a',
    messagingSenderId: '729784385247',
    projectId: 'video-call-ffd9d',
    storageBucket: 'video-call-ffd9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZrFdQ9L6NCKR0C6uC4Q17mVOTK5fu0Nc',
    appId: '1:729784385247:ios:33ce839bd8a1cdce18b36a',
    messagingSenderId: '729784385247',
    projectId: 'video-call-ffd9d',
    storageBucket: 'video-call-ffd9d.appspot.com',
    androidClientId: '729784385247-q36t906mac3m9n2k8vm5kcqsmfg01kkh.apps.googleusercontent.com',
    iosClientId: '729784385247-4fbs1nmcp1tq10ro1dbi1jfevsuq2uvu.apps.googleusercontent.com',
    iosBundleId: 'com.videocall.videoCall',
  );
}
